<?xml version="1.0" encoding="utf-8"?><Database Name="QLSV_DB" Class="DataBaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=Sow;Initial Catalog=QLSV_DB;Persist Security Info=True;User ID=sa;Trust Server Certificate=True" SettingsObjectName="WindowsFormsApp1.Properties.Settings" SettingsPropertyName="QLSV_DBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.LopHoc" Member="LopHocs">
    <Type Name="LopHoc">
      <Column Name="MaLop" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenLop" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="SiSo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="LopHoc_SinhVien" Member="SinhViens" ThisKey="MaLop" OtherKey="MaLop" Type="SinhVien" />
    </Type>
  </Table>
  <Table Name="dbo.TaiKhoan" Member="TaiKhoans">
    <Type Name="TaiKhoan">
      <Column Name="Username" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.SinhVien" Member="SinhViens">
    <Type Name="SinhVien">
      <Column Name="MaSV" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="MaLop" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Association Name="LopHoc_SinhVien" Member="LopHoc" ThisKey="MaLop" OtherKey="MaLop" Type="LopHoc" IsForeignKey="true" />
    </Type>
  </Table>
</Database>